---
title: "Demographics for table 1"
author: "Andrew McDavid"
date: "`r Sys.Date()`"
output: 
  html_document: default
  github_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

```{r}
subject = read_csv('data/subject_covariates.csv') %>% mutate(ispreterm = preterm_weeks >= 0)

nabx_polish = read_csv('data/antibiotic_exposure.csv')
```


```{r}
hospital_humilk = read_csv('data/milk_hospital.csv')
tab = table(hospital_humilk = hospital_humilk$hospital_humilk, ispreterm = hospital_humilk$ispreterm)
prop.table(tab, margin = 2)
```


```{r}
milk = read_csv('data/milk_survey.csv')
milk = milk %>% rename(milk_months = `For how many months did baby receive breast milk for more than half of feedings`) 
milk = milk %>% mutate(milk_months = case_when(is.na(milk_months)~ '0', milk_months == 'Less than 1' ~ '0.5', TRUE ~ milk_months), milk_months = as.numeric(milk_months))

milk_sum = milk %>% group_by(Subject) %>% dplyr::summarize(months_surveyed = n()*3, milk_months = mean(milk_months/3, na.rm = TRUE)*12, any_milk_quarter = mean(`Did baby receive breast milk since last visit`=='Yes', na.rm = TRUE)*4)

milk_sum = left_join(milk_sum, subject)

```

```{r}
#latex(summary( ispreterm ~ milk_months + any_milk_quarter, data = milk_sum, method = 'reverse', test = TRUE, prmsd = TRUE, continuous = 3))

ggplot(milk_sum, aes(x = preterm_weeks, y = milk_months)) + geom_point() + geom_smooth()

ggplot(milk_sum, aes(x = preterm_weeks, y = any_milk_quarter)) + geom_point() + geom_smooth()
```