---
title: "CoordinatedTCellsMicrobiota"
output: github_document
---

Data and analysis supporting "Aberrant newborn T cell and microbiota developmental trajectories predict respiratory compromise during infancy."  [Preprint](https://www.biorxiv.org/content/10.1101/736090v2)

## Contents

* data: minimally processed data -- microbiome OTU counts, T cell subpopulation abundances, subject covariates, etc
* intermediates: derived tables and output from scripts

To reproduce some results, data will need to be downloaded
[from
dbGAP](https://www.ncbi.nlm.nih.gov/projects/gap/cgi-bin/study.cgi?study_id=phs001347.v2.p1),
as some data posted here has been jittered, quantized or redacted to reduce the risk of reidentification of subjects.  The `Alias`
key will join subject-level tables to data in dbGAP.

## Scripts

* [01_make_cst](01_make_cst.md): Run DMN model on OTU and flowsom metaclusters and find best-fitting model
* [01_table1_demographics](01_table1_demographics.md): Summarize some demographic variables to generate portions of "table 1" in the paper.
* [02_network_modeling](02_network_modeling.md): Test for pairwise associations between CST, IST and flowsom metacluster
* [02_ist_cst_results](02_ist_cst_results.md): Heatmaps of IST/CST composition, associations with gestational age and postmenstrual age
* [03_development_index](03_development_index.md): prediction of PMA from microbiome and T cell subpopulations.  Developmental index.  Prediction of PRD. 
* [04_multivariate_r2](04_multivariate_r2.md): Estimates of variance explained from microbiome vs T cells, adjusting for term and PMA (figure 1)
* [04_tcell_associations](04_tcell_associations.md) PMA associations of T cell cluster abundance and broken-stick regression models of the same.  CMV/Inflammation associations between IST.
* [flowcytometry](flowcytometry/workflow_top.level.R): scripts for processing T cell flow cytometry (TPHE/ICS) to produce flowsom "metacluster" populations.  FCS files would need to be [downloaded from IMMPORT]( https://browser.immport.org/browser?path=SDY1302) to run these scripts.

These don't necessarily need to be run in order, as their inputs have been saved under `intermediates`.

To install all dependencies run `devtools::install(CoordinatedTDeps, lib = <some new directory>)` where you may wish to set `<some new directory>` to be a path besides your default `.libPaths()` to keep these packages isolated.

Run using R 3.5.1 and Bioconductor 3.7, and YMMV otherwise.


# Colophone

```{r}
devtools::load_all('CoordinatedTDeps')
devtools::session_info()
```
